
## Security Levels
# - critical
# - high
# - error
# - medium
# - moderate
# - low
# - warning
# - notes

# general:
#   level: error

codescanning:
  level: error
 
dependabot:
  level: high

licensing:
  conditions:
    ids:


secretscanning:
  level: all
